- src/Analyzer.JsonRuleEngine.UnitTests/EqualsOperatorTests.cs
- src/Analyzer.JsonRuleEngine/Operators/EqualsOperator.cs
Fixes #99.
`EqualsOperator.EvaluateExpression()` now first checks the `JToken` passed in.  If it's `null`, it immediately returns.  The value it returns is determined by whether or not the operator is negated (`equals` vs. `notEquals`).
`EqualsOperator` now also enforces a non-null value to compare against when it's created.
> Fix null-ref exception in Equals operator

- .vscode/launch.json
- .vscode/tasks.json
- CONTRIBUTING.md
- src/Analyzer.Cli/Analyzer.Cli.csproj
- src/Analyzer.Core.UnitTests/Analyzer.Core.UnitTests.csproj
- src/Analyzer.Core/Analyzer.Core.csproj
- src/Analyzer.JsonRuleEngine.FunctionalTests/Analyzer.JsonRuleEngine.FunctionalTests.csproj
- src/Analyzer.JsonRuleEngine.UnitTests/Analyzer.JsonRuleEngine.UnitTests.csproj
- src/Analyzer.TemplateProcessor.UnitTests/Analyzer.TemplateProcessor.UnitTests.csproj
- src/Analyzer.Utilities.UnitTests/Analyzer.Utilities.UnitTests.csproj
- src/Directory.Build.props
- src/NuGet.config
- Update CLI and test projects to use .NET 5
- Rename CLI output to TemplateAnalyzer (.exe and .dll)
- Add a `<Description>` field to CLI and Core projects
- Add common properties to new Build.Directory.props file
- Add VS Code configuration files for building and running
- Update documentation for contributing
> Update to .NET 5, update build metadata, include VS Code tasks

- CONTRIBUTING.md
- src/Analyzer.Cli.NuGet/Analyzer.Cli.nuspec
- src/Analyzer.Core.NuGet/Analyzer.Core.nuspec
- src/Directory.Build.props
- Adding *.nuspec files to Analyzer.Core.NuGet and Analyzer.Cli.NuGet directories
- NuGet packages can be packed with `nuget pack <.nuspec file> -p configuration=release`
- Must have nuget CLI installed on machine
- Versions have to be kept in sync manually for now.  Will open an issue to combine into a single source.
> Add nuspec files for .Core and .Cli packages

- src/Analyzer.Core/TemplateAnalyzer.cs
Closes #110 
Now the executable can be run from any directory. We don't want to scan the working directory now for new rules as the issue suggests, further design is needed to support custom rule files
> Use full file path to read built-in rules file

- src/Analyzer.Cli/CommandLineParser.cs
Remove unimplemented commands from the CLI because showing some of those options in "--help" generates confusion
> Remove unimplemented commands

- src/Analyzer.Core/TemplateAnalyzer.cs
- src/Analyzer.TemplateProcessor.UnitTests/ArmTemplateProcessorTests.cs
- src/Analyzer.TemplateProcessor/ArmTemplateProcessor.cs
- src/Analyzer.Types/TemplateContext.cs
- src/Analyzer.Utilities.UnitTests/JsonLineNumberResolverTests.cs
- src/Analyzer.Utilities/JsonLineNumberResolver.cs
- Makes and uses mapping between resources in expanded template to original template for easier line number mapping (Closes #125)
- Processes all resources language expressions once flattened
> Fix copy resources line number mapping bug

- src/Analyzer.JsonRuleEngine.UnitTests/AllOfExpressionTests.cs
- src/Analyzer.JsonRuleEngine.UnitTests/AnyOfExpressionTests.cs
- src/Analyzer.JsonRuleEngine/Expressions/AnyOfExpression.cs
Updates AnyOf operator to only fail if something was evaluated and something internal failed.  Otherwise, if nothing is evaluated, pass by default.  This ensures rules in which no paths/resource types are relevant inside an AnyOf don't result in a failure.  Closes #138.
- Update AnyOf with bug fix
- Update corresponding test for AnyOf and AllOf
> Make AnyOf not fail if nothing is evaluated

- src/Analyzer.Cli/Analyzer.Cli.csproj
- src/Analyzer.Core/Analyzer.Core.csproj
- src/Analyzer.JsonRuleEngine/Analyzer.JsonRuleEngine.csproj
- src/Analyzer.PowerShellRuleEngine/Analyzer.PowerShellRuleEngine.csproj
- src/Analyzer.TemplateProcessor/Analyzer.TemplateProcessor.csproj
- src/Analyzer.Types/Analyzer.Types.csproj
- src/Analyzer.Utilities/Analyzer.Utilities.csproj
- src/Directory.Build.targets
- Putting property group that generates code documentation (and enforces XML comments) into common *Directory.Build.targets* file
- Only applies to projects that aren't tests
- Removing from all projects that declared them manually
> Generalize XML comment enforcement

- src/Analyzer.Core/Analyzer.Core.csproj
- src/Directory.Build.targets
- Output TTK with build of Analyzer.Core (closes #154)
- Allows TTK to be included in NuGet package of just the core library
- Update output location of code documentation file (closes #155)
> Output TTK with Analyzer.Core build and fix 'dotnet publish' for debug builds

- README.md
Using shields.io service to generate a badge for the test coverage.
> Add code coverage badge to Readme

- README.md
I noticed the new CLI usage was not updated in one spot of the readme.
> Fixed CLI usage in readme

- .github/workflows/codeql-analysis.yml
This PR adds specific permissions to the existing workflows under .github/workflows/
I am trying out the [Step Security App](https://github.com/apps/step-security) on open source repositories, by forking them, installing the App on the fork, and manually creating PRs with the fixed workflows.
I have manually reviewed the changes, and they do look good to me. If something looks off, please let me know. Thanks!
> Add specific permissions to workflows

- src/Analyzer.Core.BuiltInRuleTests/TestTemplates/SQLServerAuditingSettings.badtemplate
- src/Analyzer.Core.BuiltInRuleTests/Tests/TA-000028.json
- src/Analyzer.Core/Rules/BuiltInRules.json
- src/Analyzer.TemplateProcessor.UnitTests/ArmTemplateProcessorTests.cs
- src/Analyzer.TemplateProcessor/ArmTemplateProcessor.cs
Closes #182 
Related issue: https://github.com/Azure/azure-quickstart-templates/issues/11968
In this case, not having the updated Name property in the resource is causing the problem, but we had an issue with DependsOn also some months ago
I assumed that `// Do not throw if there was another issue with evaluating language expressions` means there are other exceptions we want to ignore
I'm checking the message contents instead of the exception type because it's just a generic `TemplateValidationException`
> Throw exceptions about incorrect segment lengths and related rule improvement

- src/Analyzer.Cli.NuGet/Analyzer.Cli.nuspec
- src/Analyzer.Cli/CommandLineParser.cs
- src/Analyzer.Core.NuGet/Analyzer.Core.nuspec
- src/Analyzer.Core.UnitTests/TemplateAnalyzerTests.cs
- src/Analyzer.Core/TemplateAnalyzer.cs
- src/Analyzer.PowerShellRuleEngine.UnitTests/PowerShellRuleEngineTests.cs
- src/Analyzer.PowerShellRuleEngine/PowerShellRuleEngine.cs
- src/Analyzer.PowerShellRuleEngine/PowerShellRuleEvaluation.cs
- src/Analyzer.Reports.UnitTests/ConsoleReportWriterTests.cs
- src/Analyzer.Reports/ConsoleReportWriter.cs
- src/Analyzer.Reports/SarifReportWriter.cs
- src/Directory.Build.props
PowerShell results don't play well with SARIF right now because we're limited by the strings the ARM TTK outputs for descriptions, and the SARIF writer assumes each rule will have a standard description that's constant for all violations, in addition to a possible instance-specific message for failures.
- The JSON rules have a standard description that's the same for all rules, but lacks instance-specific messaging.
- The TTK has instance-specific messaging, but no standard description (failures simply write to the console output, and BPA captures those messages, which contain details of the specific failures).
- This means the first violation of a given PowerShell rule becomes the "standard description" for all other violations, which is really confusing when the description contains …
> Fix SARIF reporting with PowerShell results

- src/Analyzer.PowerShellRuleEngine.UnitTests/PowerShellRuleEngineTests.cs
- src/Analyzer.PowerShellRuleEngine/PowerShellRuleEngine.cs
Fixes #179.
- Always set the ExecutionPolicy to 'RemoteSigned' on Windows OS
- Save the PowerShell `Runspace` to reuse instead of keeping the same PowerShell instance (allows to not worry about clearing out previous commands before running new ones)
- Updates to PS engine tests
> Fix PowerShell engine on Windows OS

- docs/authoring-json-rules.md
- src/Analyzer.Core.BuiltInRuleTests/TestRunner.cs
- src/Analyzer.Core.BuiltInRuleTests/TestTemplates/AppServicesLogs.badtemplate
- src/Analyzer.Core.BuiltInRuleTests/Tests/TA-000001.json
- src/Analyzer.Core.UnitTests/TemplateAnalyzerTests.cs
- src/Analyzer.JsonRuleEngine.FunctionalTests/ScopeSelectionTests.cs
- src/Analyzer.JsonRuleEngine.UnitTests/ExpressionTests.cs
- src/Analyzer.JsonRuleEngine.UnitTests/JsonRuleEngineTests.cs
- src/Analyzer.JsonRuleEngine.UnitTests/JsonRuleEvaluationTests.cs
- src/Analyzer.JsonRuleEngine.UnitTests/LeafExpressionTests.cs
- src/Analyzer.JsonRuleEngine.UnitTests/NotExpressionTests.cs
- src/Analyzer.JsonRuleEngine.UnitTests/StructuredExpressionTests.cs
- src/Analyzer.JsonRuleEngine.UnitTests/TestUtilities.cs
- src/Analyzer.JsonRuleEngine/Expressions/Expression.cs
- src/Analyzer.JsonRuleEngine/Expressions/LeafExpression.cs
- src/Analyzer.JsonRuleEngine/Expressions/NotExpression.cs
- src/Analyzer.JsonRuleEngine/Expressions/StructuredExpression.cs
- src/Analyzer.JsonRuleEngine/JsonRuleEngine.cs
- src/Analyzer.JsonRuleEngine/JsonRuleEvaluation.cs
- src/Analyzer.PowerShellRuleEngine.UnitTests/PowerShellRuleEngineTests.cs
- src/Analyzer.PowerShellRuleEngine/PowerShellRuleEngine.cs
- src/Analyzer.PowerShellRuleEngine/PowerShellRuleEvaluation.cs
- src/Analyzer.Reports.UnitTests/ConsoleReportWriterTests.cs
- src/Analyzer.Reports.UnitTests/SarifReportWriterE2ETests.cs
- src/Analyzer.Reports.UnitTests/SarifReportWriterTests.cs
- src/Analyzer.Reports.UnitTests/TestCases.cs
- src/Analyzer.Reports.UnitTests/TestEvaluation.cs
- src/Analyzer.Reports/ConsoleReportWriter.cs
- src/Analyzer.Reports/SarifReportWriter.cs
- src/Analyzer.Types/IEvaluation.cs
(Closes #226)
Currently, when a template is analyzed with a particular rule, the outcome of the analysis is returned via a single `Evaluation`, which contains multiple sub-`Evaluation`s within it, representing each location (normally a resource) where the rule failed.  This causes complexity in reporting, since it's not always straightforward how to group results and line numbers into related or distinct failures.
This PR changes how rule `Expressions` return their outcomes - instead of wrapping the entire template analysis into a single `Evaluation` per `Expression`,  `Expression`s will return an `IEnumerable<Evaluation>`, where each `Evaluation` will represent a separate analysis/outcome within the template.  An `Evaluation` can still have nested `Evaluation`s within it for nested …
> Splitting rule analysis on templates into multiple Evaluations

- src/Analyzer.Core.NuGet/Analyzer.Core.nuspec
- src/Analyzer.PowerShellRuleEngine/Analyzer.PowerShellRuleEngine.csproj
- src/Analyzer.PowerShellRuleEngine/PowerShellRuleEngine.cs
- src/Directory.Build.props
Update to latest PSRule so we can specify `SessionState.Minimal` for PowerShell initial state.  This resolves an unnecessary (failed) dependency on Microsoft.Management.Infrastructure.dll in Windows packages.
---
> Fix Microsoft.Management.Infrastructure.dll failure

- src/Analyzer.Cli.FunctionalTests/CommandLineParserTests.cs
- src/Analyzer.PowerShellRuleEngine/PowerShellRuleEngine.cs
- src/Directory.Build.targets
Add back some logic to the PowerShellEngine that was originally added here: https://github.com/Azure/template-analyzer/commit/32146a5b7933875fda5126ab0e9190c2501b278c
We still need to unblock the PowerShell scripts on Windows to allow them to run. If a script is not unblocked, even if it's signed, PowerShell prompts for confirmation before executing. This prompting would throw an exception, because there's no interaction with a user that would allow for confirmation
---
> Unblock PSRule PowerShell scripts for Windows

- src/Analyzer.Cli/CommandLineParser.cs
- src/Analyzer.Reports.UnitTests/ConsoleReportWriterTests.cs
- src/Analyzer.Reports/ConsoleReportWriter.cs
- Adds indentation back to "Rules passed" line
- Clarifying scanned file count for scanning directories (see #310)
- Changes all file paths to full paths for more consistency (see #311)
> ConsoleReportWriter quick fixes

- src/Analyzer.PowerShellRuleEngine/PowerShellRuleEngine.cs
Since creating a PowerShell instance and invoking it requires extra processing, and leaves more opportunity for sporadic failures, this change removes that requirement when unblocking PSRule rule scripts during the initial creation of the PowerShell rule engine.
Instead of calling the PS command `Unblock-File`, native .NET file I/O is used directly to delete the [Alternate Data Stream (ADS)](https://learn.microsoft.com/openspecs/windows_protocols/ms-fscc/c54dec26-1551-4d3a-a0ea-4fa40f848eb3) in Windows that denotes a file was downloaded (the mechanism used for blocking PS scripts).  This is essentially what `Unblock-File` does behind the scenes, but should be much faster by doing it directly instead of through PowerShell.  After unblocking the scripts, an additional ADS is created on the …
> Unblock PSRule rules without invoking PowerShell

- src/Analyzer.Cli.FunctionalTests/CommandLineParserTests.cs
- src/Analyzer.Cli.FunctionalTests/TestCaseTemplateConstants.cs
- src/Analyzer.Utilities/TemplateDiscovery.cs
This fixes a reported customer issue with an uncaught exception in IsValidTemplate when parsing fails due to unexpected char. When scanning directories this potentially causes incomplete output to be written (e.g. incomplete SARIF).
```
Unhandled exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
---> Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: . Path '', line 1, position 1.
at Newtonsoft.Json.JsonTextReader.ParseValue()
at Microsoft.Azure.Templates.Analyzer.Cli.CommandLineParser.IsValidTemplate(FileInfo file)
at System.Linq.Enumerable.WhereArrayIterator`1.MoveNext()
at System.Linq.Enumerable.ConcatIterator`1.MoveNext()
at …
```
> Handle uncaught exception in IsValidTemplate

- .github/workflows/dotnet.yml
- src/Analyzer.BicepProcessor.UnitTests/Analyzer.BicepProcessor.UnitTests.csproj
- src/Analyzer.BicepProcessor/Analyzer.BicepProcessor.csproj
- src/Analyzer.BicepProcessor/BicepTemplateProcessor.cs
- src/Analyzer.BicepProcessor/SourceMapFeatureProvider.cs
- src/Analyzer.Cli.FunctionalTests/Analyzer.Cli.FunctionalTests.csproj
- src/Analyzer.Cli.NuGet/Analyzer.Cli.nuspec
- src/Analyzer.Cli/Analyzer.Cli.csproj
- src/Analyzer.Core.BuiltInRuleTests/Analyzer.Core.BuiltInRuleTests.csproj
- src/Analyzer.Core.NuGet/Analyzer.Core.nuspec
- src/Analyzer.Core.UnitTests/Analyzer.Core.UnitTests.csproj
- src/Analyzer.Core/Analyzer.Core.csproj
- src/Analyzer.Core/TemplateAnalyzer.cs
- src/Analyzer.JsonRuleEngine.FunctionalTests/Analyzer.JsonRuleEngine.FunctionalTests.csproj
- src/Analyzer.JsonRuleEngine.UnitTests/Analyzer.JsonRuleEngine.UnitTests.csproj
- src/Analyzer.JsonRuleEngine/Analyzer.JsonRuleEngine.csproj
- src/Analyzer.PowerShellRuleEngine.UnitTests/Analyzer.PowerShellRuleEngine.UnitTests.csproj
- src/Analyzer.PowerShellRuleEngine/Analyzer.PowerShellRuleEngine.csproj
- src/Analyzer.Reports.UnitTests/Analyzer.Reports.UnitTests.csproj
- src/Analyzer.Reports/Analyzer.Reports.csproj
- src/Analyzer.TemplateProcessing.NuGet/Analyzer.TemplateProcessing.nuspec
- src/Analyzer.TemplateProcessor.UnitTests/Analyzer.TemplateProcessor.UnitTests.csproj
- src/Analyzer.TemplateProcessor.UnitTests/ArmTemplateProcessorTests.cs
- src/Analyzer.TemplateProcessor/Analyzer.TemplateProcessor.csproj
- src/Analyzer.TemplateProcessor/ArmTemplateProcessor.cs
- src/Analyzer.TemplateProcessor/PlaceholderInputGenerator.cs
- src/Analyzer.Types/Analyzer.Types.csproj
- src/Analyzer.Utilities.UnitTests/Analyzer.Utilities.UnitTests.csproj
- src/Analyzer.Utilities/Analyzer.Utilities.csproj
Updates target to .net 7 and bicep dependency update with refactoring for use of DI for simplicity
Fixes an issue where a template fails to analyze when providing a parameters file with an incomplete set of parameters. Missing parameter values will now be generated.
---
> .NET 7, bicep update, and partial parameters

- README.md
- src/Analyzer.Cli.FunctionalTests/CommandLineParserTests.cs
- src/Analyzer.Cli/CommandLineParser.cs
- src/Analyzer.Core.UnitTests/TemplateAnalyzerTests.cs
- src/Analyzer.Core/TemplateAnalyzer.cs
In this PR I've added the `--custom-rules-json-path` CLI parameter to be able to specify a custom `Rules.Json` file location.
This is required to inject custom rules that are not part of the basic functionality included with Template Analyzer.
---
- [V] **I have read the [contribution guidelines](../CONTRIBUTING.md).**
- [V] The pull request does not introduce breaking changes.
- [V] Title of the pull request is clear and informative.
- [V] Description of the pull request is clear and informative.
- [V] I have added myself to the 'assignees'.
- [V] I have added 'linked issues' if relevant.
- [V] Pull request includes test coverage for the included changes.
> Added the ability to specify custom rules.json path

- .github/workflows/dotnet.yml
GitHub [started rolling out Ubuntu 24.04](https://github.com/actions/runner-images/issues/10636) over the last month, which our workflow picked up automatically by specifying `ubuntu-latest` as the Linux image name.
There is a breaking change between 22.04 (used previously) and 24.04 in which the mono software package is no longer installed on the image. (The note in the table at the link says software not available. `dotnet` still runs and builds without issue, so I don't quite fully understand the extent of it, but nuget commands aren't working without mono.)
This change pins Ubuntu to 22.04 while mono is missing from 24.04.
---
> Use Ubuntu 22.04 in build workflow

- .github/workflows/codeql.yml
Switching to Advanced mode for CodeQL. Hoping this will enable runs for merges from external forks.
The *codeql.yaml* file is the default file GitHub generates when switching to Advanced mode. These defaults look sufficient for our scenario, especially considering the default "simple" mode worked just fine (when it ran).
---
~~- [ ] Pull request includes test coverage for the included changes.~~
> Switch to CodeQL Advanced mode

- .github/workflows/codeql.yml
Trying to understand GitHub's detection of CodeQL setup and enablement of required workflows: renaming the CodeQL advanced setup workflow back to its default.
> Rename CodeQL workflow

- src/Analyzer.BicepProcessor.UnitTests/Analyzer.BicepProcessor.UnitTests.csproj
- src/Analyzer.BicepProcessor/Analyzer.BicepProcessor.csproj
- src/Analyzer.BicepProcessor/BicepTemplateProcessor.cs
- src/Analyzer.BicepProcessor/SourceMapFeatureProvider.cs
- src/Analyzer.Core.BuiltInRuleTests/Analyzer.Core.BuiltInRuleTests.csproj
- src/Analyzer.Core.UnitTests/Analyzer.Core.UnitTests.csproj
- src/Analyzer.JsonRuleEngine.FunctionalTests/Analyzer.JsonRuleEngine.FunctionalTests.csproj
- src/Analyzer.JsonRuleEngine.UnitTests/Analyzer.JsonRuleEngine.UnitTests.csproj
- src/Analyzer.JsonRuleEngine.UnitTests/ExistsOperatorTests.cs
- src/Analyzer.JsonRuleEngine.UnitTests/ExpressionConverterTests.cs
- src/Analyzer.JsonRuleEngine.UnitTests/HasValueOperatorTests.cs
- src/Analyzer.PowerShellRuleEngine.UnitTests/Analyzer.PowerShellRuleEngine.UnitTests.csproj
- src/Analyzer.PowerShellRuleEngine.UnitTests/PowerShellRuleEngineTests.cs
- src/Analyzer.Reports.UnitTests/Analyzer.Reports.UnitTests.csproj
- src/Analyzer.Reports.UnitTests/SarifReportWriterE2ETests.cs
- src/Analyzer.TemplateProcessor.UnitTests/Analyzer.TemplateProcessor.UnitTests.csproj
- src/Analyzer.TemplateProcessor/Analyzer.TemplateProcessor.csproj
- src/Analyzer.TemplateProcessor/ArmTemplateProcessor.cs
- src/Analyzer.Utilities.UnitTests/Analyzer.Utilities.UnitTests.csproj
- src/Directory.Packages.props
- Updating Bicep libraries current stable versions.
- Conforming to breaking changes introduced in the latest version.
- Updating other utility libraries
- Fixing some data tests (newer MSTest version was failing for some of them)
---
> Update to latest Bicep Core libraries
