Azure/template-analyzer

docs/authoring-json-rules.md, docs/built-in-bpa-rules.md, src/Analyzer.Core/Rules/BuiltInRules.json, src/Analyzer.JsonRuleEngine.UnitTests/AllOfExpressionTests.cs, src/Analyzer.JsonRuleEngine.UnitTests/AnyOfExpressionDefinitionTests.cs, src/Analyzer.JsonRuleEngine.UnitTests/AnyOfExpressionTests.cs, src/Analyzer.JsonRuleEngine.UnitTests/ExpressionConverterTests.cs, src/Analyzer.JsonRuleEngine.UnitTests/JsonRuleEngineTests.cs, src/Analyzer.JsonRuleEngine/Converters/ExpressionConverter.cs, src/Analyzer.JsonRuleEngine/Expressions/AnyOfExpression.cs, src/Analyzer.JsonRuleEngine/Schema/AllOfExpressionDefinition.cs, src/Analyzer.JsonRuleEngine/Schema/AnyOfExpressionDefinition.cs, src/Analyzer.JsonRuleEngine/Schema/ExpressionDefinition.cs, src/Analyzer.JsonRuleEngine/Schema/LeafExpressionDefinition.cs
Add support of anyOf operator (Closes #13)
Add tests for anyOf
Add anyOf as keyword when parsing rules
Add built-in rule that uses anyOf (Closes #48 )
=> Add support for anyOf operator

docs/authoring-json-rules.md, src/Analyzer.Core/Rules/BuiltInRules.json, src/Analyzer.JsonRuleEngine.UnitTests/ExpressionConverterTests.cs, src/Analyzer.JsonRuleEngine.UnitTests/JsonRuleEngineTests.cs, src/Analyzer.JsonRuleEngine.UnitTests/LeafExpressionDefinitionTests.cs, src/Analyzer.JsonRuleEngine.UnitTests/RegexOperatorTests.cs, src/Analyzer.JsonRuleEngine/JsonRuleEngine.cs, src/Analyzer.JsonRuleEngine/JsonRuleEngineException.cs, src/Analyzer.JsonRuleEngine/Operators/RegexOperator.cs, src/Analyzer.JsonRuleEngine/Schema/LeafExpressionDefinition.cs
Add support of regex operator (Closes #18)
Add tests for regex
Update documentation
Add built in rule: API App should only be accessible over HTTPS (Closes #76)
=> Add support for regex operator

docs/authoring-json-rules.md, src/Analyzer.JsonRuleEngine.UnitTests/EqualsOperatorTests.cs, src/Analyzer.JsonRuleEngine.UnitTests/ExistsOperatorTests.cs, src/Analyzer.JsonRuleEngine.UnitTests/ExpressionConverterTests.cs, src/Analyzer.JsonRuleEngine.UnitTests/HasValueOperatorTests.cs, src/Analyzer.JsonRuleEngine.UnitTests/InOperatorTests.cs, src/Analyzer.JsonRuleEngine.UnitTests/JsonRuleEngineTestsUtilities.cs, src/Analyzer.JsonRuleEngine.UnitTests/LeafExpressionDefinitionTests.cs, src/Analyzer.JsonRuleEngine.UnitTests/RegexOperatorTests.cs, src/Analyzer.JsonRuleEngine.UnitTests/TestUtilities.cs, src/Analyzer.JsonRuleEngine/Operators/EqualsOperator.cs, src/Analyzer.JsonRuleEngine/Operators/ExistsOperator.cs, src/Analyzer.JsonRuleEngine/Operators/HasValueOperator.cs, src/Analyzer.JsonRuleEngine/Operators/InOperator.cs, src/Analyzer.JsonRuleEngine/Schema/LeafExpressionDefinition.cs
=> Add support for 'in' operator

docs/built-in-bpa-rules.md, src/Analyzer.Core/Rules/BuiltInRules.json
Closes #77.  Closes #78.
Adds rule JSON logic and recommendations at rule overview page.  Also adds missing recommendation for #76.
=> Add rules for requiring HTTPS in web/sites resources

src/Analyzer.Cli/CommandLineParser.cs
Add line number, file path, and parameters path to CLI output
=> Add line number, file path, and parameters path to CLI output

src/Analyzer.JsonRuleEngine.UnitTests/RegexOperatorTests.cs, src/Analyzer.JsonRuleEngine/Operators/RegexOperator.cs
Fix null reference exception in Regex operator (Closes #101)
=> Fix null reference exception in Regex operator

docs/built-in-bpa-rules.md, src/Analyzer.Core.UnitTests/TemplateAnalyzerTests.cs, src/Analyzer.Core/Rules/BuiltInRules.json, src/Analyzer.TemplateProcessor.UnitTests/ArmTemplateProcessorTests.cs, src/Analyzer.TemplateProcessor/ArmTemplateProcessor.cs, src/Analyzer.Utilities.UnitTests/JsonLineNumberResolverTests.cs, src/Analyzer.Utilities/JsonLineNumberResolver.cs
- Map resources that depend on other resources to support rules that use the where clause (Closes #71)
- Report the correct line number when mapping the result to original template
- Add tests
- Add built-in rule "Latest TLS version should be used in your Web App" (Closes #94)
=> Support writing rules that depend on the relationship between resources

docs/built-in-bpa-rules.md, src/Analyzer.Core/Rules/BuiltInRules.json
- Update built in rules URIs to correct url
- Add following built in rules: 
- Latest TLS version should be used in your Function App (Closes #93)
- Latest TLS version should be used in your API App (Closes #74)
- Diagnostic logs in App Services should be enabled (Closes #73)
- Managed identity should be used in your Web App (Closes #70)
- Managed identity should be used in your Function App (Closes #69)
- Managed identity should be used in your API App (Closes #68)
- FTPS only should be required in your Web App (Closes #67)
- FTPS only should be required in your Function App (Closes #66)
- FTPS only should be required in your API App (Closes #65)
- Transparent Data Encryption on SQL databases should be enabled (Closes #53)
- CORS should not allow every resource to access your Web …
=> Add rules that require copy resources feature

docs/built-in-bpa-rules.md, src/Analyzer.Cli/CommandLineParser.cs, src/Analyzer.Core/Rules/BuiltInRules.json
- Print all inner exception messages
- Only print line numbers when the rule failed
=> Small CLI output improvements

src/Analyzer.Cli.NuGet/Analyzer.Cli.nuspec, src/Analyzer.Core.NuGet/Analyzer.Core.nuspec, src/Directory.Build.props
Update version to 0.0.2-alpha to prepare for release
=> Update version to 0.0.2-alpha

src/Analyzer.Core.BuiltInRuleTests/TestRunner.cs, src/Analyzer.Core.BuiltInRuleTests/TestTemplates/AppServices.badtemplate, src/Analyzer.Core.BuiltInRuleTests/TestTemplates/AutomationAccountsVariables.badtemplate, src/Analyzer.Core.BuiltInRuleTests/TestTemplates/Kubernetes.badtemplate, src/Analyzer.Core.BuiltInRuleTests/Tests/AppServiceApiApp_RestrictCORSAccess.json, src/Analyzer.Core.BuiltInRuleTests/Tests/AppServiceFunctionApp_RestrictCORSAccess.json, src/Analyzer.Core.BuiltInRuleTests/Tests/AppServiceWebApp_RestrictCORSAccess.json, src/Analyzer.Core.BuiltInRuleTests/Tests/AutomationAccounts_Variables_Encrypted.json, src/Analyzer.Core.BuiltInRuleTests/Tests/Kubernetes_Must_Restrict_Network_Access.json
- Authorized IP ranges should be defined on Kubernetes Services
- Automation account variables should be encrypted
- CORS should not allow every resource to access your API App
- CORS should not allow every resource to access your Function Apps
- CORS should not allow every resource to access your Web Applications
Working towards #153
=> Add tests for the below built-in rules

docs/authoring-json-rules.md, docs/built-in-bpa-rules.md, src/Analyzer.Core.BuiltInRuleTests/TestTemplates/KubernetesVersions.badtemplate, src/Analyzer.Core.BuiltInRuleTests/Tests/Kubernetes_Upgrade_Non-Vulnerable_Version.json, src/Analyzer.Core/Rules/BuiltInRules.json, src/Analyzer.JsonRuleEngine.UnitTests/AllOfExpressionDefinitionTests.cs, src/Analyzer.JsonRuleEngine.UnitTests/AnyOfExpressionDefinitionTests.cs, src/Analyzer.JsonRuleEngine.UnitTests/ExpressionConverterTests.cs, src/Analyzer.JsonRuleEngine.UnitTests/HasValueOperatorTests.cs, src/Analyzer.JsonRuleEngine.UnitTests/InOperatorTests.cs, src/Analyzer.JsonRuleEngine.UnitTests/NotExpressionDefinitionTests.cs, src/Analyzer.JsonRuleEngine.UnitTests/NotExpressionTests.cs, src/Analyzer.JsonRuleEngine.UnitTests/RegexOperatorTests.cs, src/Analyzer.JsonRuleEngine/Converters/ExpressionConverter.cs, src/Analyzer.JsonRuleEngine/Expressions/Expression.cs, src/Analyzer.JsonRuleEngine/Expressions/LeafExpression.cs, src/Analyzer.JsonRuleEngine/Expressions/NotExpression.cs, src/Analyzer.JsonRuleEngine/Operators/ExistsOperator.cs, src/Analyzer.JsonRuleEngine/Operators/HasValueOperator.cs, src/Analyzer.JsonRuleEngine/Operators/InOperator.cs, src/Analyzer.JsonRuleEngine/Operators/RegexOperator.cs, src/Analyzer.JsonRuleEngine/Schema/AllOfExpressionDefinition.cs, src/Analyzer.JsonRuleEngine/Schema/AnyOfExpressionDefinition.cs, src/Analyzer.JsonRuleEngine/Schema/ExpressionDefinition.cs, src/Analyzer.JsonRuleEngine/Schema/LeafExpressionDefinition.cs, src/Analyzer.JsonRuleEngine/Schema/NotExpressionDefinition.cs
- Add not operator (Closes #90)
- Update tests for all operators
- Add tests for not operator
- Update documentation for not operator
- Add rule Kubernetes_Upgrade_Non-Vulnerable_Version and its tests(Closes #49)
=> Add not operator support

src/Analyzer.TemplateProcessor.UnitTests/ArmTemplateProcessorTests.cs, src/Analyzer.TemplateProcessor/PlaceholderInputGenerator.cs
Closes #181 
More info on the environment function: https://docs.microsoft.com/en-us/azure/azure-resource-manager/templates/template-functions-deployment#environment
For the placeholder object, I used the example in the public documentation, as it matches the one in the library tests
=> Add environment properties to the placeholder deployment metadata

.github/workflows/dotnet.yml
Add a new workflow file for defining a new GitHub Action for building the repo.
This doesn't give us a way to view code coverage yet.
=> Create workflow for build action

README.md, src/Analyzer.Cli.NuGet/Analyzer.Cli.nuspec, src/Analyzer.Core.NuGet/Analyzer.Core.nuspec, src/Directory.Build.props
- Update version to 0.1.0
- add SARIF option to README
=> Update version to 0.1.0

.github/ISSUE_TEMPLATE/bug_report.yml, .github/ISSUE_TEMPLATE/config.yml, .github/ISSUE_TEMPLATE/feature_request.yml, .github/ISSUE_TEMPLATE/rule_request.yml, .github/pull_request_template.md, .github/workflows/codeql-analysis.yml, .github/workflows/dotnet.yml, CONTRIBUTING.md
Add PR section to the Contributing guide and specify the branch strategy
Add PR Template
Add Issue/Bug and Feature Request Template
Closes #216
=> Define Branch Strategy; Add Issue + PR Templates; Update Contributing Guide w/ PR Section

src/Analyzer.Cli.NuGet/Analyzer.Cli.nuspec, src/Analyzer.Core.NuGet/Analyzer.Core.nuspec, src/Directory.Build.props
=> Update version to 0.1.2

.github/ISSUE_TEMPLATE/bug_report.yml, .github/ISSUE_TEMPLATE/config.yml, .github/ISSUE_TEMPLATE/feature_request.yml, .github/ISSUE_TEMPLATE/rule_request.yml, .github/pull_request_template.md, .github/workflows/codeql-analysis.yml, .github/workflows/dotnet.yml, CONTRIBUTING.md, src/Analyzer.Cli.NuGet/Analyzer.Cli.nuspec, src/Analyzer.Core.NuGet/Analyzer.Core.nuspec, src/Analyzer.Reports.UnitTests/SarifReportWriterE2ETests.cs, src/Analyzer.Reports.UnitTests/SarifReportWriterTests.cs, src/Analyzer.Reports/SarifReportWriter.cs, src/Analyzer.Utilities.UnitTests/JsonLineNumberResolverTests.cs, src/Analyzer.Utilities/JsonLineNumberResolver.cs, src/Directory.Build.props
=> Prepare release 0.1.2

.github/CODEOWNERS, .github/ISSUE_TEMPLATE/feature_request.yml, .github/pull_request_template.md
Add CODEOWNERS to the repo. The codeowners will be assigned to the PR when a new PR is made.
Followed instructions: https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners
---
=> Create CODEOWNERS file; Edit Feature/Improvement template; Edit PR template

README.md, src/Analyzer.Cli/Analyzer.Cli.csproj, src/Analyzer.Cli/CommandLineParser.cs, src/Analyzer.Core/Analyzer.Core.csproj, src/Analyzer.Core/TemplateAnalyzer.cs, src/Analyzer.JsonRuleEngine/Analyzer.JsonRuleEngine.csproj, src/Analyzer.JsonRuleEngine/JsonRuleEngine.cs, src/Analyzer.PowerShellRuleEngine/PowerShellRuleEngine.cs, src/Analyzer.TemplateProcessor/Analyzer.TemplateProcessor.csproj, src/Analyzer.TemplateProcessor/ArmTemplateProcessor.cs, src/Analyzer.Types/Analyzer.Types.csproj, src/Analyzer.Types/IRuleEngine.cs
Closes #144 
Working towards #157 too
Documentation followed: https://docs.microsoft.com/en-us/dotnet/core/extensions/logging
Changes in the CLI are not ideal, we need to do #207 
I'm not sure if we want to replace all the remaining `Console.WriteLine`s for `logger.LogInformation`, I assumed we don't
I think ideally we should pass the logger to `TemplateAnalyzer` and the engines on class creation, but the `TemplateAnalyzer` instance is created before processing the CLI input options, and I'm not sure if we want to change that now
Regarding tests, #28 has to be done before we can add proper tests for this PR
---
=> Add verbose option to the CLI, and general improvements to local logging

src/Analyzer.Cli.FunctionalTests/CommandLineParserTests.cs, src/Analyzer.Cli/Loggers/SummaryLogger.cs
Improve the Cli Analysis Output to be clearer, faster, and easier to read
Adds to PR #242 
---
=> Cli Improve Analysis output

README.md, src/Analyzer.Cli.FunctionalTests/CommandLineParserTests.cs, src/Analyzer.Cli/CommandLineParser.cs, src/Analyzer.Cli/ExitCode.cs, src/Analyzer.Cli/Loggers/SummaryLogger.cs, src/Analyzer.Cli/Loggers/SummaryLoggerProvider.cs, src/Analyzer.Core.BuiltInRuleTests/TestRunner.cs, src/Analyzer.Core.UnitTests/TemplateAnalyzerTests.cs, src/Analyzer.Core/TemplateAnalyzer.cs, src/Analyzer.JsonRuleEngine.UnitTests/JsonRuleEngineTests.cs, src/Analyzer.JsonRuleEngine/JsonRuleEngine.cs, src/Analyzer.Reports.UnitTests/SarifReportWriterE2ETests.cs, src/Analyzer.Reports/SarifReportWriter.cs
Refactor CLI
- Extract commonalities between template and directory analysis into setup and cleanup functions (closes #207).
- Move parsing of configuration to CLI (closes #233).
- Improved directory searching for template files - use .NET platform to filter for JSON files
- [NEW] Analyze-Template no longer requires the file to have a ".json" file extension; only the JSON properties will be validated.
Other improvements
- Update template validation to only read what's necessary of a file, instead of reading the whole file into memory first.
- Polish summary output
- Update text for counts
- Fix counts in some scenarios
- Remove "Unable to analyze n files" from summary, as that line is already a summary by itself.
---
This checklist is used to make sure that common guidelines for a pull …
=> CLI refactoring and other improvements

.github/workflows/codeql-analysis.yml, .github/workflows/dotnet.yml, .vscode/launch.json, .vscode/tasks.json, CONTRIBUTING.md, README.md, src/Analyzer.Cli.FunctionalTests/Analyzer.Cli.FunctionalTests.csproj, src/Analyzer.Cli.NuGet/Analyzer.Cli.nuspec, src/Analyzer.Cli/Analyzer.Cli.csproj, src/Analyzer.Cli/CommandLineParser.cs, src/Analyzer.Core.BuiltInRuleTests/Analyzer.Core.BuiltInRuleTests.csproj, src/Analyzer.Core.NuGet/Analyzer.Core.nuspec, src/Analyzer.Core.UnitTests/Analyzer.Core.UnitTests.csproj, src/Analyzer.Core/Analyzer.Core.csproj, src/Analyzer.Core/TemplateAnalyzer.cs, src/Analyzer.JsonRuleEngine.FunctionalTests/Analyzer.JsonRuleEngine.FunctionalTests.csproj, src/Analyzer.JsonRuleEngine.UnitTests/Analyzer.JsonRuleEngine.UnitTests.csproj, src/Analyzer.JsonRuleEngine/JsonRuleEngine.cs, src/Analyzer.PowerShellRuleEngine.UnitTests/Analyzer.PowerShellRuleEngine.UnitTests.csproj, src/Analyzer.PowerShellRuleEngine/Analyzer.PowerShellRuleEngine.csproj, src/Analyzer.PowerShellRuleEngine/PowerShellRuleEngine.cs, src/Analyzer.Reports.UnitTests/Analyzer.Reports.UnitTests.csproj, src/Analyzer.TemplateProcessor.UnitTests/Analyzer.TemplateProcessor.UnitTests.csproj, src/Analyzer.Types/IRuleEngine.cs, src/Analyzer.Utilities.UnitTests/Analyzer.Utilities.UnitTests.csproj, src/Directory.Build.props, src/TTK.targets
- Update project to .NET 6
- When building, add support for generating a ~~single, self-contained executable~~ self-contained build for multiple platforms
- The PowerShell library does not support packing into a single executable right now - it throws an exception upon initialization.  See https://github.com/PowerShell/PowerShell/issues/13540.
- Update PowerShell engine to unblock PS module files.  PS always attempts to get confirmation to execute, even when files are signed.  Unblocking ahead of time prevents this issue.
- Minor code updates to support single executable (`Assembly.GetExecutingAssembly().Location` doesn't work in this scenario)
- Code will be ready when PowerShell supports it, or there is a workaround.
- Update the CLI NuGet spec file to support self-contained build
- …
=> Update to .NET 6, Support Self-Contained Platform-Specific Releases

src/Directory.Build.props
=> Update version to 0.2.0

src/Analyzer.Cli.FunctionalTests/Analyzer.Cli.FunctionalTests.csproj, src/Analyzer.Cli.FunctionalTests/CommandLineParserTests.cs, src/Analyzer.Cli.FunctionalTests/Tests/Invalid.bicep, src/Analyzer.Cli/CommandLineParser.cs, src/Analyzer.Cli/ExitCode.cs, src/Analyzer.Core.NuGet/Analyzer.Core.nuspec, src/Analyzer.Core/TemplateAnalyzer.cs
Minor additions to CLI missed for bicep updates.
=> CLI fixes/additions for bicep

src/Analyzer.Cli.FunctionalTests/CommandLineParserTests.cs, src/Analyzer.Cli.FunctionalTests/ValidTemplateConstants.cs, src/Analyzer.Cli/CommandLineParser.cs, src/Analyzer.Cli/Loggers/ConsoleLoggerFormatter.cs, src/Analyzer.Cli/Loggers/CustomFormatter.cs, src/Analyzer.Cli/Loggers/SummaryLogger.cs
Closes #241
Closes #157
Documentation followed: https://docs.microsoft.com/en-us/dotnet/core/extensions/console-log-formatter
An example before:
After:
---
=> Improve the console output

src/Analyzer.JsonRuleEngine.FunctionalTests/RuleParsingTests.cs, src/Analyzer.PowerShellRuleEngine/Analyzer.PowerShellRuleEngine.csproj, src/Analyzer.PowerShellRuleEngine/PSRuleHostContext.cs, src/Analyzer.PowerShellRuleEngine/PowerShellRuleEngine.cs, src/Analyzer.PowerShellRuleEngine/PowerShellRuleEvaluation.cs
- Updates as discussed based on the latest fixes and interface improvements.
---
=> Updates based on PSRule v2.3.0-B0130 fixes

src/Analyzer.PowerShellRuleEngine/Analyzer.PowerShellRuleEngine.csproj, src/Analyzer.PowerShellRuleEngine/PowerShellRuleEngine.cs, src/Analyzer.PowerShellRuleEngine/SecurityBaseline.Rule.json
- Update reference to baseline via path include.
---
=> Reference baseline

src/Directory.Build.props
=> Increment tool version to 0.3

src/Analyzer.Core.NuGet/Analyzer.Core.nuspec, src/Analyzer.PowerShellRuleEngine/Analyzer.PowerShellRuleEngine.csproj, src/Analyzer.PowerShellRuleEngine/PowerShellRuleEngine.cs, src/Directory.Build.props
Merge bug fix for version 0.3.1
=> Release version 0.3.1

src/Analyzer.TemplateProcessor.UnitTests/ArmTemplateProcessorTests.cs, src/Analyzer.TemplateProcessor/PlaceholderInputGenerator.cs
Closes #285
---
- [] Pull request includes test coverage for the included changes.
=> Add missing values to placeholder metadata

docs/built-in-bpa-rules.md, src/Analyzer.Core.BuiltInRuleTests/Tests/TA-000029/TA-000029.json, src/Analyzer.Core.BuiltInRuleTests/Tests/TA-000030/TA-000030.json, src/Analyzer.Core.BuiltInRuleTests/Tests/TA-000030/VMs.json, src/Analyzer.Core.BuiltInRuleTests/Tests/TA-000031/StorageAccounts.json, src/Analyzer.Core.BuiltInRuleTests/Tests/TA-000031/TA-000031.json, src/Analyzer.Core/Rules/BuiltInRules.json
Classic Storage and Classic VMs are old resource types that shouldn't be used anymore.  These new rules disallow usage of those resource types, and suggest the modern resource types instead.
---
=> Add rules to disallow use of Classic VM and Classic Storage resource types

src/Analyzer.TemplateProcessor/ArmTemplateProcessor.cs
Improve the information logged when there's a problem parsing a template output. The output value was showing empty in all the logs
---
=> Fix log message on output parsing failure

src/Analyzer.Cli.FunctionalTests/CommandLineParserTests.cs, src/Analyzer.Cli/CommandLineParser.cs, src/Analyzer.Cli/Loggers/ConsoleLoggerFormatter.cs, src/Analyzer.Cli/Loggers/ConsoleLoggerFormatterOptions.cs, src/Analyzer.Cli/Loggers/SummaryLogger.cs, src/Analyzer.TemplateProcessor/ArmTemplateProcessor.cs
Closes #294 
Details in the issue and the commit messages
---
=> Reduce noise in the CLI output

docs/authoring-json-rules.md, src/Analyzer.Cli/CommandLineParser.cs, src/Analyzer.Core/Rules/BuiltInRules.json, src/Analyzer.JsonRuleEngine.UnitTests/JsonRuleEvaluationTests.cs, src/Analyzer.JsonRuleEngine/JsonRuleEvaluation.cs, src/Analyzer.JsonRuleEngine/Schemas/RuleDefinition.cs, src/Analyzer.PowerShellRuleEngine.UnitTests/PowerShellRuleEngineTests.cs, src/Analyzer.PowerShellRuleEngine/PowerShellRuleEvaluation.cs, src/Analyzer.Reports.UnitTests/SarifReportWriterTests.cs, src/Analyzer.Reports.UnitTests/TestCases.cs, src/Analyzer.Reports.UnitTests/TestEvaluation.cs, src/Analyzer.Reports/SarifReportWriter.cs, src/Analyzer.Types/IEvaluation.cs
Closes #198 
More details on the issue and in the commit messages
I followed the guideline recommended in the issue, mostly keeping the rule names as short as possible, with a maximum of 40 characters. The format and names are very similar to the rule IDs the tool used to have (https://github.com/Azure/template-analyzer/commit/74af183c1c1d717a7deedfdd46aa71d42518a2b6): `<the resource type name, an abbreviation of it, or a description>.<the change that should be done, or key words if that's too long>`
---
=> Define rule names

docs/built-in-bpa-rules.md
https://learn.microsoft.com/en-us/azure/defender-for-cloud/iac-vulnerabilities will link to this page, and it was considered necessary to explain the levels before showing the rule information
---
=> Explain severity levels in rule docs

CONTRIBUTING.md
Updates to contribution guide to keep it current.
=> Maintaining the contribution guide

src/Analyzer.Cli.FunctionalTests/CommandLineParserTests.cs, src/Analyzer.Core.UnitTests/TemplateAnalyzerTests.cs, src/Analyzer.PowerShellRuleEngine/baselines/RepeatedRulesBaseline.Rule.json, src/Analyzer.PowerShellRuleEngine/baselines/SecurityBaseline.Rule.json
Adding AZR-000082 to dupe list
=> Adding AZR-000082 to dupe list

src/Analyzer.Core.NuGet/Analyzer.Core.nuspec, src/Analyzer.PowerShellRuleEngine/Analyzer.PowerShellRuleEngine.csproj, src/Analyzer.TemplateProcessing.NuGet/Analyzer.TemplateProcessing.nuspec, src/Analyzer.TemplateProcessor/Analyzer.TemplateProcessor.csproj, src/Analyzer.TemplateProcessor/ArmTemplateProcessor.cs, src/Directory.Build.props
Updating dependencies for [CVE-2023-29331](https://github.com/advisories/GHSA-555c-2p6r-68mm).
=> Release 0.5.2, CVE update

src/Analyzer.TemplateProcessor/PlaceholderInputGenerator.cs
Updates the placeholder parameter generation code to directly navigate and parse only the parameter section of the target template. This is opposed to the old behavior where the entirety of the template was parsed and then just the parameter data was read.
=> Avoid parsing whole template when generating placeholder parameters

azure-pipelines.yml, src/Analyzer.BicepProcessor/Analyzer.BicepProcessor.csproj, src/Analyzer.BicepProcessor/BicepTemplateProcessor.cs, src/Analyzer.BicepProcessor/SourceMapFeatureProvider.cs, src/Analyzer.JsonRuleEngine.UnitTests/JsonRuleEngineTests.cs, src/Analyzer.JsonRuleEngine/JsonRuleEngine.cs
If an empty inclusion object is present then all rules are excepted.
Bicep dependency update
---
=> Small fix for configuration file and bicep version bump

src/Directory.Build.props
=> Update version to 0.6.0

src/Directory.Build.props
Updating version to prepare for v0.8.0 release.
---
=> Update version to prepare for release

.github/workflows/dotnet.yml, src/Analyzer.Reports.NuGet/Analyzer.Reports.nuspec, src/Analyzer.Reports/Analyzer.Reports.nuspec
We've gotten a request for publishing Analyzer.Reports via NuGet. This adds support for that package.
---
=> Added nuget package for Analyzer.Reports

src/Directory.Build.props
=> Prepare release 0.8.3

src/Directory.Build.props
=> Update version to 0.8.5
